### ISSUE TITLE
getshares returns socket.error: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by schaefer0** [Azelphur/ownCloud-share-tools#3]
I am looking for help for diagnosing this problem. The url is valid.
$ ocsharetools --user mahali --pass mahali --url http://kronos.haystack.mit.edu/owncloud --disable-ssl-verification getshares

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/requests-2.7.0-py3.2.egg/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.2/dist-packages/requests-2.7.0-py3.2.egg/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.2/http/client.py", line 970, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.2/http/client.py", line 1008, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.2/http/client.py", line 966, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.2/http/client.py", line 811, in _send_output
    self.send(msg)
  File "/usr/lib/python3.2/http/client.py", line 749, in send
    self.connect()
  File "/usr/local/lib/python3.2/dist-packages/requests-2.7.0-py3.2.egg/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.2/dist-packages/requests-2.7.0-py3.2.egg/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.2/dist-packages/requests-2.7.0-py3.2.egg/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/usr/local/lib/python3.2/dist-packages/requests-2.7.0-py3.2.egg/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
socket.error: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

**Comment by schaefer0** [comment]
It was a firewall problem.
